osism/openstack-image-manager

etc/images.yml

see https://github.com/rancher/os/releases/tag/v1.5.1
Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>

Remove RancherOS v1.4.1, due CVE-2019-5736

---

etc/images.yml

- Update URL of Debian 10.9 (20210327).
- Add Debian 10.10 (20210619).
- Add Debian 10.10.1 (20210624).

Update Debian images

---

etc/images.yml
src/manage.py

* use mirror everywhere where the images are not kept for long in the upstream.
* remove all old versions
* add OpenSUSE Leap 15.3

Preparations for 1.0.0 release

---

etc/images.yml

Added image for Debian 11. There is a new image URL as Debian no longer provides special OpenStack images because the generic images work as well.

Add image for Debian 11 Bullseye

---

src/manage.py

Fixes https://github.com/osism/openstack-image-manager/issues/206
Use Glance's inbuilt import-image method instead of manually creating a task, in return avoiding a lot of issues in newer Openstack releases as well as embracing the intended Glance image import worklow.
I also added two commits cleaning up the corresponding code parts.

Switch to Interoperable Image Import

---

etc/images.yml

- Update Debian Buster to version 10.12
- Update Debian Bullseye to version 11.3

Update Debian images to 10.12 and 11.3

---

requirements.txt
src/manage.py
test/test_manage.py

Closes https://github.com/osism/openstack-image-manager/issues/228 and https://github.com/osism/openstack-image-manager/issues/213.
Create a single class that contains the whole functionality of the
Image-Manager which allows for easy exporting.
The Image-Manager can be invoked by running the `main()` method.
All unittests are updated accordingly.
The requirements for `python-glanceclient` and `os-client-config` are
removed, as it was forgotten in https://github.com/osism/openstack-image-manager/pull/236.
Do not delete image properties that start with `os_*` since they are set by glance.
Signed-off-by: Simon Hensel <simon.hensel@inovex.de>

Refactor code: Create a class for the Image-Manager

---

clouds.yml.sample
documentation/source/usage.rst
secure.yml.sample
src/manage.py
test/test_manage.py

This is the default of the openstacksdk itself.
Closes osism/openstck-image-manager#244

Change default cloud name to openstack

---

requirements.txt
src/manage.py
src/mirror.py
src/share.py
src/table.py
tox.ini

Closes https://github.com/osism/openstack-image-manager/issues/314 and https://github.com/osism/openstack-image-manager/issues/240.
Use a Munch object instead of oslo.CONF, so most of the codebase can stay the same.
`--latest` is now `False` by default, to bring it in line with all other bool options.
To pass multiple image names, `--name` has to be called multiple times.
* Remove `oslo.config` from requirements.txt
* Add Tox environment for table.py

Switch to Typer as CLI

---

src/manage.py

- only load .yml or .yaml files
- if yaml.load fails skip with YAMLError
Signed-off-by: Ralf Heiringhoff <ralf.heiringhoff@plusserver.com>

more resilient etc/images handling

---

src/manage.py
test/integration/test_manage_api.py
test/unit/test_manage.py

This adds the possibility to use latest pointer URLs (e.g. from Debian, Ubuntu or Rocky) to check if a new image is available. This mechanism is optionally usable by setting the image version to `'latest'` and providing the URL of the checksums file in the corresponding yaml file.
Due to the absence of version numbers when using latest, the last modification date of the upstream image file gets retrieved and used as the `internal_version` image property. If this date cannot be retrieved, set the `internal_version` to `'latest'` temporarily and use the creation date from OpenStack as soon as a newer image gets uploaded.
A possible config in images.yml would look like this:
```yaml
versions:
- version: 'latest'
url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd6 …
```

Use latest pointer URLs

---

.github/clouds.yml
.github/workflows/run-integration-tests.yml
doc/source/usage.rst

Closes osism/openstack-image-manager#316

Document use of OS_CLIENT_CONFIG_FILE

---

etc/images/flatcar.yml

Part of osism/openstack-image-manager#341

Remove old flatcar images and add latest stable release

---

etc/images/cirros.yml

Part of osism/openstack-image-manager#341

Use cirros 0.6.0

---

Pipfile
Pipfile.lock
etc/schema.yaml
requirements.txt
src/manage.py
test/unit/test_manage.py

Closes #360.
The YAML schema includes the same fields as the `check_image_metadata()` method.
Some fields such as `uuid_validity`, `provided_until`, `image_source` or `image_description` are mandatory according to the spec, but are not yet included into the image.yaml files.
So these fields are marked as not required for now.
Merge after #387 and #388.

Validate yaml schema with yamale

---

etc/images/centos.yml
etc/images/debian.yml
etc/images/ubuntu.yml

2022-11-13 21:04:01 | ERROR    | validate_yaml_schema:748 - Error validating data 'etc/images/debian.yml' with 'etc/schema.yaml'
2022-11-13 21:04:01 | ERROR    | validate_yaml_schema:750 - 	images.1.versions.0.build_date: '2022-11-09' is not a day.
2022-11-13 21:04:01 | ERROR    | validate_yaml_schema:750 - 	images.1.versions.0.build_date: '2022-11-09' is not a timestamp.

Fix 'is not a day/timestamp' issue

---

etc/images/almalinux.yml
etc/images/centos.yml
etc/images/cirros.yml
etc/images/clearlinux.yml
etc/images/debian.yml
etc/images/fedora-coreos.yml
etc/images/fedora.yml
etc/images/flatcar.yml
etc/images/gardenlinux.yml
etc/images/kubernetes.yml
etc/images/opensense.yml
etc/images/opensuse.yml
etc/images/rockylinux.yml

For flavors  it should  set the  following values:
hw_rng:allowed=True
hw_rng:rate_bytes - The allowed amount of bytes for the the guest to read from the host’s entropy per period. hw_rng:rate_period
Signed-off-by: Mathias Fechner <fechner@osism.tech>

Add: hw_rng_model: virtio to Linux Distro's

---

setup.cfg

This way it is possible to use the image definition included
within the project directly after the installation via PyPi.

Add etc/images/*.yml to package data

---

etc/images/almalinux.yml
etc/images/centos.yml
etc/images/debian.yml
etc/images/ubuntu.yml

images.1.versions.0.build_date: '2022-11-18' is not a day. images.1.versions.0.build_date: '2022-11-18' is not a timestamp.

Fix schema validation error

---

src/manage.py
test/integration/test_manage_api.py
test/unit/test_manage.py

Closes #503 and #505.
Also remove the `--name` parameter, since we now have the more flexible and powerful `--filter`.

Fix hiding and deletion of rotated images

---

etc/images/debian.yml
etc/schema.yaml
playbooks/real-world.yml
src/manage.py
test/unit/test_manage.py

Disabled images can be used via the new --force parameter.
This way it is possible to add new images that should not be deployed by default.

Add enable parameter to be able to disable specific images

---

.zuul.yaml

No security breach, but rather a loss of the zuul server database was the reason for the rotation.
Signed-off-by: Tim Beermann <beermann@osism.tech>

Rotate zuul secrets

---

src/mirror.py
src/update.py

Talos image introduced a .tar.gz file type.
Added gz as a fileextension canidate that should be decompressed.
Signed-off-by: Tim Beermann <beermann@osism.tech>

Add gz file extension

---

openstack_image_manager/manage.py
playbooks/real-world.yml

With the parameter --keep it is possible to keep versions of defined images that are not longer defined itself.
Processing image 'Garden Linux 576.12'
Skipping image 'Garden Linux 576.12' (only importing the latest version from type multi) Processing image 'Garden Linux 934.8'
Processing unmanaged image 'Garden Linux 934.6'
The image 'Garden Linux 934.6' is not deleted because undefined versions of defined images are kept

Allow to keep undefined versions of defined images

---

etc/images/octavia.yml

Disabled by default. This way it is possible to use the image manager to manage the amphora images. This will avoid the use of an additional playbook for this task.

Re-add octavia image

---

.zuul.yaml
mypy.ini
openstack_image_manager/manage.py
openstack_image_manager/mirror.py
openstack_image_manager/table.py
test/unit/test_manage.py

This commit adds type hints where necessary and
renames a local variable from 'images' to 'imgs',
because it shared the name with a function parameter,
which threw off automatic type checking.
Also added the mypy.ini to exclude the doc/ folder
for now.

Fix mypy typing problems and enable mypy zuul job

---

openstack_image_manager/manage.py

Pull request #618 introduced type hint problems which were not caught, because the mypy pipeline was merged after the PR was created. This commit fixes two little type hint oversights.

Fix type hints for mypy pipeline

---

doc/getting_started.md
openstack_image_manager/manage.py
playbooks/real-world.yml
test/integration/test_manage_api.py
test/unit/test_manage.py

This change will remove the --validate option from the image-manager and its unit tests.
fixes #441

Removing --validate typer/command-line option from image-manager

---

doc/quickstart.md

Currently the quickstart guide references a `--name` flag in the example command which is not an implemented flag (anymore?). I've replaced it with the equivalent `--filter` usage instead.

Update example command in quickstart guide

---

openstack_image_manager/manage.py
openstack_image_manager/update.py

Preserve original URL when mirroring image in
update script (resolves #634).
Developed-by: Matthias Büchse <matthias.buechse@cloudandheat.com>
Submitted-by: Sven Kieske <kieske@osism.tech>
Signed-off-by: Matthias Büchse <matthias.buechse@cloudandheat.com>
Signed-off-by: Sven Kieske <kieske@osism.tech>

Preserve original URL when mirroring image

---

etc/schema.yaml
openstack_image_manager/manage.py
test/unit/test_manage.py

Previously, old images were rotated and finally deleted after a certain number of newer images were released.
This commit adds a flag for the yml definition to stop automatic deletion.
Fixes #342

Add yml flag to skip deletion of oldest image for selected images

---

etc/images/almalinux.yml
etc/images/centos.yml
etc/images/clearlinux.yml
etc/images/debian.yml
etc/images/fedora.yml
etc/images/kubernetes.yml
etc/images/octavia.yml
etc/images/rockylinux.yml
etc/images/talos.yml
etc/images/ubuntu.yml
etc/schema.yaml
openstack_image_manager/manage.py
openstack_image_manager/update.py
test/unit/test_manage.py

This change will unify the build_date of all
images to a datetime object instead of a "stringify" datetime like object.
previously implemented logic to work with both formats, has also been dropped.
fixes #638

Unify the build_date of all image references

---

etc/images/almalinux.yml
etc/images/centos.yml
etc/images/rockylinux.yml

As discussed in the SCS project, we no longer want to use EL8 images by default.

Disable el8 images by default

---

openstack_image_manager/update.py

Resolves #639 and includes many minor improvements (including a somewhat alternative approach to #633).

Automatically resolve latest/current URLs for Debian/Ubuntu

---

etc/images/fedora.yml

Disable Fedora 37 image by default

---

openstack_image_manager/update.py

This way it is possible to use e.g. /swift/v1/AUTH_123/ as URL prefix for download URLs when not working with DNS for bucket/project names.

Allow to set a swift prefix in the update script

---

openstack_image_manager/manage.py

The `X | Y` notation[^1] for typing in Python was introduced in Python 3.10 and makes `openstack-image-manager` fail on older Python versions such as 3.9:
```
$ openstack-image-manager --help
Traceback (most recent call last):
...
) -> Image | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
This PR uses the backwards-compatible `typing.Union` instead which achieves the same and makes `openstack-image-manager` usable on older Python 3 releases as well.
[^1]: https://peps.python.org/pep-0604/

Provide compatibility with Python 3 versions older than 3.10

---

etc/images/almalinux.yml
etc/images/centos.yml
etc/images/debian.yml
etc/images/rockylinux.yml
etc/images/ubuntu.yml

This is a workaround for all existing images that will not be updated in the (near) future.
Related to osism/issues#913

Add mirror_url to all existing image definitions

---

openstack_image_manager/main.py

The module `openstack_image_manager.manage` was renamed to `openstack_image_manager.main` in a previous commit. A condition checking the module name was fixed to reflect this change.

Fix usage of outdated module name

---

etc/images/almalinux.yml
etc/images/centos.yml
etc/images/cirros.yml
etc/images/clearlinux.yml
etc/images/debian.yml
etc/images/fedora.yml
etc/images/flatcar.yml
etc/images/gardenlinux.yml
etc/images/kubernetes.yml
etc/images/opensuse.yml
etc/images/opnsense.yml
etc/images/osism.yml
etc/images/rockylinux.yml
etc/images/talos.yml
etc/images/ubuntu.yml
etc/schema.yaml
openstack_image_manager/main.py

This also removes the hypervisor CLI parameter. It makes no sense to change the hypervisor for all images as the hypervisor is defined for each image.

Set the hypervisor_type for all images to qemu

---

.github/workflows/validate-configuration.yml
etc/schema.yaml
openstack_image_manager/main.py
test/unit/test_manage.py

Every call of openstack_image_manager will now validate the image yamls against the schema before managing the images. (Previously check defaulted to ``False`` and exited without managing the images)
Furthermore add the option ``--check-only`` used if only the validation is desired but not managing the images (for example in CI pipelines)

Add separator to schema.yaml
