osism/openstack-image-manager

etc/images.yml

Now it contains the correct repo files.

Update for openSUSE Leap 15.1 image

---

etc/images.yml

(feat) add rancheros v1.5.4

---

etc/images.yml
src/mirror.py

* openSUSE Kubic has been renamed to openSUSE MicroOS
* added openSUSE Kubic kubeadm
* added openSUSE Kubic containerhost

Add openSUSE MicroOS images

---

etc/images.yml

Co-authored-by: Johannes Kastl <kastl@b1-systems.de>

Add tumbleweed image

---

etc/images.yml

(feat) add rancheros v1.5.5

---

etc/images.yml

Remove coreos

---

.github/workflows/validate-config.yml
.yamale.yml

github: add 'Validate configuration' workflow

---

etc/images.yml

Add cirros 0.5.1

---

etc/images.yml

Update ubuntu images

---

etc/images.yml

Update debian images

---

etc/images.yml

Add centos stream image

---

etc/images.yml

Drop unused OSISM base image

---

etc/images.yml

Add missing shortname argument for Fedora CoreOS

---

.github/workflows/mirror-images.yml

github: add 'Mirror images' workflow

---

.github/workflows/mirror-images.yml

github: fix self trigger of mirror-images

---

etc/images.yml

Add flatcar container linux image

---

src/mirror.py

mirror: fix directory handling

---

etc/images.yml

Add fedora coreos 32 image

---

etc/images.yml

Cleanup old images

---

etc/images.yml

Add openstack octavia amphora image for rocky

---

src/check.py
tox.ini

Add script to check urls

---

etc/images.yml
src/check.py

Cleanup images, add latest http check & drop arch linux

---

etc/images.yml

Add rancheros 1.5.6

---

README.md

README: add taskflow_executor glance configuration parameter

---

src/manage.py

Add hide/deactivate/delete CLI arguments

---

.github/dependabot.yml

github: add dependabot configuration

---

src/manage.py

Add parameter to only import the latest version of an image

---

src/manage.py

Fix handling of latest image with the latest argument

---

etc/images.yml

Add all available octavia images

---

etc/images.yml

Fix octavia versions

---

src/manage.py

Set image_original_user property

---

.yamale.yml
etc/images.yml

Set hw_rng_model=virtio on ubuntu images

---

src/manage.py

Add os:distro tag

---

src/manage.py

Check min_disk size of existing images

---

etc/images.yml

Fix wrong min_disk values

---

.yamale.yml
src/manage.py

Add image-build-date property

---

src/manage.py

Set min_disk to image size if min_disk is not set or is wrong

---

.github/workflows/check-python-syntax.yml
.github/workflows/check-yaml-syntax.yml
.github/workflows/pr-labeler.yml
.github/workflows/validate-configuration.yml

github: rename workflows

---

etc/images.yml

Update amhpora images & add amphora tag

---

etc/images.yml

Disable amphora images before victoria

---

etc/images.yml

Update ubuntu bionic & focal images

---

src/manage.py

Do not delete the 'stores' property

---

src/manage.py

Change log level for 'Image %s should be deleted' from info to debug

---

src/manage.py

Add --name argument

---

etc/images.yml

Remove cirros 0.4.0 image

---

etc/images.yml

Add debian 10.7.0 image

---

etc/images.yml

Add rancher 1.5.7 image

---

etc/images.yml

Add fedora 33 image

---

etc/images.yml

Use debian version 9.13.11

---

.github/workflows/mirror-images.yml
etc/images.yml

Add flatcar 2605.10.0 image & improve 'Mirror images' workflow

---

etc/images.yml

Signed-off-by: Johannes Kastl <kastl@b1-systems.de>
The 10.7.0 image is showing errors during automatic upgrade via ansible:
```
fatal: [debian10-01]: FAILED! => {"changed": false, "msg": "'/usr/bin/aptitude safe-upgrade' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\nYou must correct your GRUB install devices before proceeding:\n\n  dpkg-reconfigure grub-pc\ndpkg: error processing package grub-pc (--configure):\n installed grub-pc package post-installation script subprocess returned error exit status 1\nErrors were encountered while processing:\n grub-pc\n", "rc": 255, "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nReading extended state information...\nInitializing package states...\nWriting extended state …
```

etc/images.yml: add Debian 10.8.0

---

etc/images.yml

Signed-off-by: Johannes Kastl kastl@b1-systems.de

add new CentOS7 image (2009)

---

etc/images.yml

Signed-off-by: Johannes Kastl <kastl@b1-systems.de>

add new CentOS8 image (2011)

---

src/manage.py

Related issue: https://github.com/SovereignCloudStack/openstack-image-manager/issues/169
Signed-off-by: Tobias Fischer <tobias.fischer@cloudandheat.com>

Fix image renaming after upload

---

.github/workflows/check-python-syntax.yml
.github/workflows/check-yaml-syntax.yml
.github/workflows/mirror-images.yml
.github/workflows/validate-configuration.yml
.github/yamllint.yml

github: improve workflows

---

.yamale.yml
src/manage.py

Related issue: https://github.com/SovereignCloudStack/openstack-image-manager/issues/168

Add support for 'visibility' per version

---

.yamale.yml
src/manage.py

Signed-off-by: Tobias Fischer <tobias.fischer@cloudandheat.com>

Add support for the os_hidden property

---

README.md
src/manage.py

betacloud -> osism

---

.github/workflows/mirror-images.yml

master -> main

---

etc/images.yml

Use openstack wallaby amphora image

---

etc/images.yml

Add missing directory

---

etc/images.yml

Fix opensuse shortnames + versions

---

etc/images.yml

Add cirros 0.5.2

---

etc/images.yml

Add missing shortnames

---

README.md

README: add mirror note

---

etc/images.yml

Add Rocky 8 image

---

etc/images.yml

Add garden linux image

---

etc/images.yml

Add missing bucket

---

etc/images.yml

Fix garden linux url

---

etc/images.yml

Add kubernetes CAPI 1.22.0 image

---

README.md

README: change the tag of the managed images

---

etc/images.yml

Rename Ubuntu Minimal images

---

etc/images.yml

Flatcar Container Linux is not a multi image

---

etc/images.yml

Clear Linux is not a multi image

---

etc/images.yml

Garden Linux: fix login user

---

Pipfile
Pipfile.lock
requirements.txt

Add pipfile

---

etc/images.yml
src/mirror.py

And update all versions where necessary to mirror them.

Use minio.services.osism.tech

---

src/manage.py

In the future it will be possible to keep only
the latest version in the config.

Support the new config format

---

README.md
src/manage.py

Add use-raw-images parameter

---

etc/images.yml

Update some images & add fedora 35

---

etc/images.yml

Add the debian images to the mirror service

---

etc/images.yml

Add debian shortnames & missing debian 8 mirror

---

etc/images.yml

Add gardenlinux 576.1

---

.github/workflows/validate-configuration.yml
.yamale.yml

Add classification + expiration parameters to the version class

---

.yamale.yml
etc/images.yml

This also fixes a few broken URLs/versions.
Related-to #215

Add checksum parameter

---

etc/images.yml

Update k8s capi images

---

.github/workflows/check-python-syntax.yml
.github/workflows/check-yaml-syntax.yml
.github/workflows/validate-configuration.yml

partly: osism/issues#85
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

github: run branch builds on main only

---

.github/workflows/run-unit-tests.yml

- Add a GitHub action to run unit tests.
- Closes issue#241
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

Github actions: Add run unit test

---

etc/images.yml

- Added image for Ubuntu 22.04
- Added image for Ubuntu 22.04 Minimal

Add images for Ubuntu 22.04

---

etc/images.yml

Signed-off-by: Johannes Kastl <kastl@b1-systems.de>

etc/images.yml: add Fedora CoreOS 36

---

etc/images/fedora.yml

Co-authored-by: Johannes Kastl <kastl@b1-systems.de>

Add fedora 36 image

---

etc/images/rockylinux.yml

Co-authored-by: Johannes Kastl <kastl@b1-systems.de>

Add rocky 8.6 image

---

.github/workflows/mirror-images.yml

github: run mirror-images on changes in etc/images/*.yml

---

.github/workflows/validate-configuration.yml

github: run validate-configuration on changes in etc/images/*.yml

---

etc/images/kubernetes.yml

Update kubernetes cluster API images

---

src/check.py
src/manage.py
src/mirror.py
src/table.py

Use os.path.join

---

etc/images/ubuntu.yml

Add ubuntu 22.04

---

etc/images/ubuntu.yml

Fix broken ubuntu 20.04 URLs

---

README.md

README: link documentation

---

etc/images/centos.yml

Add centos stream 9 image

---

etc/images/opensuse.yml

Co-authored-by: Johannes Kastl <kastl@b1-systems.de>

Add opensuse leap 15.4

---

src/manage.py

Closes #278.
Signed-off-by: Simon Hensel <simon.hensel@inovex.de>

Allow to specify multiple images with --name

---

.github/workflows/run-integration-tests.yml
clouds.yml

github: install glance service

---

doc/source/requirements.rst

doc: add s3 storage backend to the requirements

---

src/manage.py

Makes the changes from #320 more consistent.
Signed-off-by: Simon Hensel <simon.hensel@inovex.de>

Exit with return code 1 if any errors occur duting execution

---

.github/workflows/build-container-image.yml
.github/workflows/check-docker-syntax.yml
Containerfile
Dockerfile
scripts/build.sh
scripts/push.sh
src/__init__.py

Closes osism/openstack-image-manager#350

Build container image

---

Pipfile
Pipfile.lock
requirements.txt
src/manage.py
test/integration/test_manage_api.py
test/unit/test_manage.py

Closes #318.
The log format is up for debate, it is currently:
`TIME | LEVEL | FUNCTION:LINE - MESSAGE`
so for example:
`2022-10-11 10:05:01 | INFO     | process_image:272 - Processing image 'Debian 11 (20220911)'`

Switch to loguru for logging

---

etc/images/almalinux.yml

Update almalinux images

---

etc/images/rockylinux.yml

Update rockylinux images

---

.github/workflows/update-images.yml
.yamale.yml
Pipfile
Pipfile.lock
etc/images/almalinux.yml
etc/images/rockylinux.yml
requirements.txt
src/update.py
tox.ini

Add update script

---

.github/workflows/update-images.yml
etc/images/rockylinux.yml

Automate the update of rockylinux images

---

etc/images/ubuntu.yml
src/update.py

Automate the update of ubuntu images

---

Pipfile
etc/images/centos.yml
src/update.py

Automate the update of centos images

---

.github/workflows/update-images.yml
etc/images/debian.yml
src/update.py

Automate the update of debian images

---

src/manage.py

Allow the use of a single images file

---

src/manage.py

Do not try to join with a directory

---

src/manage.py
test/integration/test_manage_api.py
test/unit/test_manage.py

Filter images with a regex on their name
Closes #335

Add --filter

---

src/manage.py
test/unit/test_manage.py

This method is there to shrink main() and execute the validation of the images independently of their processing.

Add process_images method

---

etc/images/flatcar.yml

Fix small error in the new flatcar url

---

etc/images/almalinux.yml
etc/images/amphora.yml
etc/images/centos.yml
etc/images/cirros.yml
etc/images/clearlinux.yml
etc/images/debian.yml
etc/images/fedora-coreos.yml
etc/images/fedora.yml
etc/images/flatcar.yml
etc/images/gardenlinux.yml
etc/images/kubernetes.yml
etc/images/opensense.yml
etc/images/opensuse.yml
etc/images/rockylinux.yml
etc/images/ubuntu.yml
etc/schema.yaml

Add replace_frequency arguments

---

etc/images/almalinux.yml
etc/images/centos.yml
etc/images/cirros.yml
etc/images/clearlinux.yml
etc/images/debian.yml
etc/images/fedora-coreos.yml
etc/images/fedora.yml
etc/images/flatcar.yml
etc/images/gardenlinux.yml
etc/images/kubernetes.yml
etc/images/opensense.yml
etc/images/opensuse.yml
etc/images/rockylinux.yml
etc/images/ubuntu.yml
etc/schema.yaml

Add uuid_validity arguments

---

src/update.py

Set the build_date when updating an image

---

doc/source/notes.rst

doc: add "Mapping to SCS Image Metadata"

---

etc/images/almalinux.yml
etc/images/centos.yml
etc/images/cirros.yml
etc/images/clearlinux.yml
etc/images/debian.yml
etc/images/fedora-coreos.yml
etc/images/fedora.yml
etc/images/flatcar.yml
etc/images/gardenlinux.yml
etc/images/kubernetes.yml
etc/images/opensense.yml
etc/images/opensuse.yml
etc/images/rockylinux.yml
etc/images/ubuntu.yml
etc/schema.yaml

Add provided_until arguments

---

etc/images/almalinux.yml
etc/images/centos.yml
etc/images/cirros.yml
etc/images/clearlinux.yml
etc/images/debian.yml
etc/images/fedora-coreos.yml
etc/images/fedora.yml
etc/images/flatcar.yml
etc/images/gardenlinux.yml
etc/images/kubernetes.yml
etc/images/opensense.yml
etc/images/opensuse.yml
etc/images/rockylinux.yml
etc/images/ubuntu.yml
etc/schema.yaml

Add missing build_date arguments

---

setup.cfg

Add license to setup.cfg

---

README.md

README: add pypi badges

---

README.md

README: fix badge link

---

doc/source/notes.rst
src/manage.py
test/unit/test_manage.py

Set image_source

---

doc/source/notes.rst
etc/schema.yaml
src/manage.py
test/unit/test_manage.py

Add image_description arguments

---

.markdownlint.json
.zuul.yaml
README.md

Add markdownlint to the zuul pipeline

---

doc/source/quickstart.md

partly #419
Signed-off-by: Tim Beermann <beermann@osism.tech>
Co-authored-by: Ramona Beermann <ramona.beermann@osism.tech>

Add quickstart guide documentation.

---

doc/source/configuration.md

Close osism/openstack-image-manager#423

Add configuration.md for the new documentation

---

doc/source/contribute.md

Add contribute.md for the new documentation

---

doc/source/overview.md

Close osism/openstack-image-manager#420

Add overview.md for the new documentation

---

doc/source/getting_started.md

Close osism/openstack-image-manager#422

Add getting_started.md for the new documentation

---

doc/source/requirements.md

- Close osism/openstack-image-manager#421

Add requirements.md for the new documentation

---

etc/images/gardenlinux.yml

Use garden linux 576.12 image

---

crawler/LICENSE
crawler/crawler/core/exporter.py
crawler/etc/config.yaml
crawler/image-crawler.py

replaced static template path with config variable, added new year to crawler license file
Signed-off-by: Christian Stelter <christian.stelter@plusserver.com>

replaced static template path with config variable, added new year

---

doc/source/overview.md

Change Titel to Overview

---

etc/images/cirros.yml

cirros: add version 0.6.1

---

_config.yml

Add jekyll configuration for gh pages

---

.github/workflows/update-images.yml

Do not fail fast when updating the images

---

crawler/crawler/core/database.py
crawler/crawler/core/exporter.py
crawler/crawler/core/main.py
crawler/crawler/git/base.py
crawler/crawler/updater/service.py
crawler/crawler/web/directory.py
crawler/crawler/web/generic.py
crawler/historian.py
crawler/image-crawler.py

Part of osism/openstack-image-manager#470

Autoformat crawler syntax with black

---

src/manage.py

Closes osism/openstack-image-manager#453

Fix managed images filter

---

.zuul.yaml
playbooks/integration-test.yml
playbooks/pre-integration-test.yml

We'll add a real real-world-test.

zuul: rename real-world-test to integration-test

---

playbooks/real-world.yml
src/manage.py

Also autoformat manage.py syntax

zuul: validate real-world images

---

openstack_image_manager/manage.py

uuid_validity will be used to configure the last X images that should be kept.
Closes osism/openstack-image-manager#568
Closes osism/openstack-image-manager#51

Handle hide/delete of last-X images

---

etc/images/opensense.yml

The current one doesn't work with the used CDN there and Requests.

Change opnsense mirror

---

etc/images/debian.yml

https://www.debian.org/News/2023/20230610

Enable debian 12 image

---

openstack_image_manager/manage.py

Closes #617, see the issue for more information

Abort when images are stuck in queued state

---

openstack_image_manager/manage.py
test/unit/test_manage.py

This commit adds a new command flag option to
check the environment image build dates against
the definition files.
Fixes #416

Add option to check image age in environment

---

openstack_image_manager/manage.py
openstack_image_manager/mirror.py

Error handling corrections and small code cleanup of unused stuff

---

playbooks/real-world.yml

zuul: do not upload talos & opnsense images

---

README.md

Closes osism/openstack-image-manager#747

README: fix documentation URL

---

etc/schema.yaml

Add mirror_url to schema

---

openstack_image_manager/update.py

Keep track of the current_url when updating an image definition

---

etc/images/clearlinux.yml
etc/images/fedora.yml
etc/images/flatcar.yml
etc/images/gardenlinux.yml
etc/images/opensuse.yml
etc/images/opnsense.yml
etc/images/talos.yml

Change source to mirror_url/url

---

test/integration/fixtures/test_image.yml

warning  truthy value should be one of [false, true]  (truthy)

Fix yamllint truthy warnings

---

etc/images/gardenlinux.yml

Also remove old gardenlinux versions.

Add gardenlinux 1443.2

---

openstack_image_manager/main.py
test/unit/test_manage.py

Add field "image_name" to metadata

---

openstack_image_manager/main.py

Fixes https://github.com/osism/issues/issues/1242

Fix specifying single image file

---

etc/images/opnsense.yml

Add opnsense 25.1 image

---

etc/schema.yaml

schema: add hw_vif_multiqueue_enabled to meta information
